### ISSUE TITLE
guzzle with php 8.2 issue

### ISSUE THREAD

**Issue by krava77** [modmore/guzzle7#1]
Hello!
the component is using guzzle 7.3 which does not support php 8.2.
Could you update it or how can I resolve this issue?
is it enough to update guzzle to the latest version using Composer ?
![изображение](https://github.com/modmore/guzzle7/assets/784804/b6713f1c-26f5-436c-8d6a-857c8de2c76b)

MODX: 3.0.3, php 8.2.*, nginx

**Comment by Mark-H** [comment]
Disable `display_errors` in your php.ini. 

The root issue there [has been fixed already for MODX 3.0.4/3.1](https://github.com/modxcms/xpdo/pull/252).

It does look like I missed a bunch of Guzzle releases so it's probably time to create a new build.

**Comment by Mark-H** [comment]
Guzzle 7.8 is now available. That's not going to fix the specific errors you posted as that's a core MODX issue, but does offer wider PHP support.
